{{- if .Values.infrastructure.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec: #container information
      containers:
      - name: rabbitmq #image 
        image: {{ .Values.infrastructure.rabbitmq.image }}
        env: #image details
        - name: RABBITMQ_DEFAULT_USER #username
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.existingSecretName | default "visionrag-platform-secrets" }}
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS #Pass
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.existingSecretName | default "visionrag-platform-secrets" }}
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS #value for prometheus_port opening
          value: "-rabbitmq_prometheus prometheus_port 15692"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "15692"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
  type: ClusterIP
{{- end }}
